name: Check style and links

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  LYCHEE_VERSION: v0.15.0

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install lychee
        run: |
          curl -fLO "https://github.com/lycheeverse/lychee/releases/download/${LYCHEE_VERSION}/lychee-${LYCHEE_VERSION}-x86_64-unknown-linux-gnu.tar.gz"
          tar -xvzf lychee-${LYCHEE_VERSION}-x86_64-unknown-linux-gnu.tar.gz
          rm lychee-${LYCHEE_VERSION}-x86_64-unknown-linux-gnu.tar.gz
          mv lychee /usr/local/bin

      - run: npm ci
      - run: npm run lint
